### ISSUE TITLE
搭建好，测试已经成功，但是入库不推送！

### ISSUE THREAD

**Issue by Awhitedressy** [Ccccx159/Emby_Notifier#10]
[2024-08-18 01:11:50] [media.py|process_media|307] [INFO] : Received message: 新 再见，地球 - S1, Ep6 - 第 6 集 在 Awhitedress-影视中心
[2024-08-18 01:11:50] [my_httpd.py|worker|22] [ERROR] : Traceback (most recent call last):
  File "/usr/src/myapp/my_httpd.py", line 20, in worker
    media.process_media(msg)
  File "/usr/src/myapp/media.py", line 323, in process_media
    raise e
  File "/usr/src/myapp/media.py", line 319, in process_media
    md.parse_info(emby_media_info)
  File "/usr/src/myapp/media.py", line 176, in parse_info
    self.media_detail_["server_url"] = emby_media_info["Server"]["Url"]
                                       ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
KeyError: 'Url'

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 356, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    b't3 12.1.2\nAS:2048\nHL:19\n\n'
      ^
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 356, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    b'\x16\x03\x01'
      ^
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 356, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadHttpMessage: 400, message:
  Pause on PRI/Upgrade:

    b''
      ^
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 356, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    b'\x16\x03\x01'
      ^
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 356, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    b'\x16\x03\x01'
      ^
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 356, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    b't3 12.1.2\nAS:2048\nHL:19\n\n'

**Comment by Ccccx159** [comment]
本来想做企业微信中点击影片推送信息的卡片可以自动跳转到emby，但是emby推送的信息中不包含Serverl Url，导致字段缺失，这个忘记改回去了😰我先直接去掉这个功能的修复一下，后面在考虑怎么处理吧

**Comment by Awhitedressy** [comment]
> 本来想做企业微信中点击影片推送信息的卡片可以自动跳转到emby，但是emby推送的信息中不包含Serverl Url，导致字段缺失，这个忘记改回去了😰我先直接去掉这个功能的修复一下，后面在考虑怎么处理吧

感谢，改下@下，我去重拉镜像。感谢佬

**Comment by Ccccx159** [comment]
hub 上镜像已更新～

![](https://github.com/user-attachments/assets/b6fe4bb6-0003-4c8b-b4ea-e334d8e7a1ae)

![](https://github.com/user-attachments/assets/e64b26c9-48c5-4e59-9701-db02eaff49bb)
