### ISSUE TITLE
剧集入库不通知，电影正常

### ISSUE THREAD

**Issue by Awhitedressy** [Ccccx159/Emby_Notifier#15]
[2024-09-29 21:55:37] [media.py|process_media|310] [INFO] : Received message: 新 仙逆 - S1, Ep56 - 第 56 集 在 Awhitedress-影视中心
[2024-09-29 21:55:37] [tvdb_api.py|login|32] [INFO] : TVDB login successful.
[2024-09-29 21:55:37] [media.py|_get_id|58] [INFO] : {"Name": "仙逆", "Type": "Episode", "PremiereYear": 2024, "ProviderIds": {"Tvdb": "433335"}, "Series": 56, "Season": 1}
[2024-09-29 21:55:38] [media.py|get_details|212] [ERROR] : No stills found for TV 223911 S1E56.
[2024-09-29 21:55:38] [my_httpd.py|worker|22] [ERROR] : Traceback (most recent call last):
  File "/usr/src/myapp/my_httpd.py", line 20, in worker
    media.process_media(msg)
  File "/usr/src/myapp/media.py", line 326, in process_media
    raise e
  File "/usr/src/myapp/media.py", line 323, in process_media
    md.get_details()
  File "/usr/src/myapp/media.py", line 213, in get_details
    raise Exception(err)
Exception: No stills found for TV 223911 S1E56.

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 362, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    b'\x03'
      ^
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 362, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    b'\x16\x03\x01'
      ^
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 362, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    b'\x16\x03\x01'
      ^
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 362, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    b't3 12.1.2\nAS:2048\nHL:19\n\n'
      ^
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 362, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    b'\x16\x03\x01'
      ^
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 362, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadHttpMessage: 400, message:
  Pause on PRI/Upgrade:

    b''

**Comment by Ccccx159** [comment]
等我放假看看

**Comment by Ccccx159** [comment]
> Exception: No stills found for TV 223911 S1E56.

看起来像是仙逆的第56集被导入的时候，tmdb还没有他的still图片。我刚刚搜索了一下，目前的detail中是存在"still_path"这个元数据的。

<img width="444" alt="image" src="https://github.com/user-attachments/assets/0ffd1520-b350-4fc5-b559-531db7977b92">

可以观察一下其他电视剧是否推送正常？

**Comment by Awhitedressy** [comment]
> > Exception: No stills found for TV 223911 S1E56.
> 
> 看起来像是仙逆的第56集被导入的时候，tmdb还没有他的still图片。我刚刚搜索了一下，目前的detail中是存在"still_path"这个元数据的。
> 
> <img alt="image" width="444" src="https://private-user-images.githubusercontent.com/35327600/372712464-0ffd1520-b350-4fc5-b559-531db7977b92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4Mzc3NDksIm5iZiI6MTcyNzgzNzQ0OSwicGF0aCI6Ii8zNTMyNzYwMC8zNzI3MTI0NjQtMGZmZDE1MjAtYjM1MC00ZmM1LWI1NTktNTMxZGI3OTc3YjkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAyVDAyNTA0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4NDU5N2YzMzc4ZmEyODA5MDU0NWY1YTFmZDQxZTBmNmIxOTUzODA5NzlkMzRlZDA4NDFjZmM4M2YxNzViZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YMxAe6SvIu2BiBFuPReLlLnZPYHlEYWzh6ujoLqBGjY">
> 可以观察一下其他电视剧是否推送正常？

我下载入库之前的老的电视剧 是正常。都是新出的没有办法推送。。 这种办法有办法让他 跳过么、tg推送只有海报 这个没有不影响

**Comment by Ccccx159** [comment]
我这两天看看，现在在外地，不是很方便，可能不一定能及时处理哈

**Comment by Awhitedressy** [comment]
> 我这两天看看，现在在外地，不是很方便，可能不一定能及时处理哈

好的，谢谢c大。
