### ISSUE TITLE
网络没问题，就是报错HTTPError: 400

### ISSUE THREAD

**Issue by hulinhao233** [Ccccx159/Emby_Notifier#26]
███████╗███╗   ███╗██████╗ ██╗   ██╗    ███╗   ██╗ ██████╗ ████████╗██╗███████╗██╗███████╗██████╗

██╔════╝████╗ ████║██╔══██╗╚██╗ ██╔╝    ████╗  ██║██╔═══██╗╚══██╔══╝██║██╔════╝██║██╔════╝██╔══██╗

[2024-12-16 11:41:11] [main.py|require_check|94] [INFO] : Checking requirements...

█████╗  ██╔████╔██║██████╔╝ ╚████╔╝     ██╔██╗ ██║██║   ██║   ██║   ██║█████╗  ██║█████╗  ██████╔╝

██╔══╝  ██║╚██╔╝██║██╔══██╗  ╚██╔╝      ██║╚██╗██║██║   ██║   ██║   ██║██╔══╝  ██║██╔══╝  ██╔══██╗

███████╗██║ ╚═╝ ██║██████╔╝   ██║       ██║ ╚████║╚██████╔╝   ██║   ██║██║     ██║███████╗██║  ██║

╚══════╝╚═╝     ╚═╝╚═════╝    ╚═╝       ╚═╝  ╚═══╝ ╚═════╝    ╚═╝   ╚═╝╚═╝     ╚═╝╚══════╝╚═╝  ╚═╝

Welcome to Emby Notifier!

Author: xu4n_ch3n

Version: 3.0.4

Update Time: 2024-10-02

Description: Emby Notifier is a media notification service for Emby Server. Now Jellyfin Server is alreay supported.

Repository: https://github.com/Ccccx159/Emby_Notifier

Checking environment variables...

--------Media Database info:

TMDB_API_TOKEN: (req) ******************

TVDB_API_KEY:   (opt) None

--------Telegram Bot info:

TG_BOT_TOKEN:   (req) 7*************

TG_CHAT_ID:     (req) -1002**************

--------Wechat App info:

WECHAT_CORP_ID: (req) None

WECHAT_CORP_SECRET: (req) None

WECHAT_AGENT_ID: (req) None

WECHAT_USER_ID: (req) None

--------Log info:

LOG_LEVEL:      (opt) INFO

LOG_EXPORT:     (opt) True

LOG_PATH:       (opt) /volume1/docker/Emby-Notifier/

[2024-12-16 11:41:11] [main.py|require_check|97] [INFO] : Checking TMDB_API_TOKEN...

[2024-12-16 11:41:12] [tmdb_api.py|login|34] [INFO] : TMDB login successful.

[2024-12-16 11:41:12] [main.py|require_check|101] [INFO] : Checking TG_BOT_TOKEN...

[2024-12-16 11:41:13] [tgbot.py|bot_authorization|52] [INFO] : Telegram bot authorization successful. Current bot: EmbyNewBot

[2024-12-16 11:41:13] [main.py|require_check|105] [INFO] : Checking TG_CHAT_ID...

[2024-12-16 11:41:15] [tgbot.py|get_chat|80] [ERROR] : {"method": "getChat", "chat_id": "-1002318400679"}

[2024-12-16 11:41:15] [tgbot.py|get_chat|81] [ERROR] : Telegram getChat failed. Error: 400 Client Error: Bad Request for url: https://api.telegram.org/bot7620958668:AAENzcDQCw5EOQBolocbJmHIRjnT8lpTP7o/

[2024-12-16 11:41:15] [main.py|require_check|114] [ERROR] : 400 Client Error: Bad Request for url: https://api.telegram.org/bot7620958668:AAENzcDQCw5EOQBolocbJmHIRjnT8lpTP7o/

Traceback (most recent call last):

  File "/usr/src/myapp/main.py", line 123, in <module>

    require_check()

  File "/usr/src/myapp/main.py", line 115, in require_check

    raise e

  File "/usr/src/myapp/main.py", line 106, in require_check

    tgbot.get_chat()

  File "/usr/src/myapp/tgbot.py", line 82, in get_chat

    raise e

  File "/usr/src/myapp/tgbot.py", line 67, in get_chat

    res.raise_for_status()

  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status

    raise HTTPError(http_error_msg, response=self)

requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.telegram.org/bot76209********/

**Comment by Ccccx159** [comment]
看起来好像没啥问题，重新申请一个 bot 试试？

**Comment by TNOK364364** [comment]
我也遇到这个问题了，在这个网址后面加个getUpdates就行了：https://api.telegram.org/bot76209********/getUpdates

**Comment by HEITU515** [comment]
请问您问题解决了吗？我也遇到同样的问题。

**Comment by Ccccx159** [comment]
> 请问您问题解决了吗？我也遇到同样的问题。

@HEITU515  你在 #40 中提到的问题已经解决了吗？

@HEITU515  @hulinhao233  关于这个 400 的错误 我尝试使用了你们日志中提供的 chat_id 进行查询，telegram返回的错误均为无法找到对应的chat，请关注 chat_id 的正确性

~~~bash
curl -X POST https://api.telegram.org/bot170**************************J7bpoK90UnlY/ -H "Content-Type: application/json" -d '{"method":"getChat", "chat_id":"-1002318400679"}'

{"ok":false,"error_code":400,"description":"Bad Request: chat not found"}
~~~

~~~bash
curl -X POST https://api.telegram.org/bot170**************************J7bpoK90UnlY/ -H "Content-Type: application/json" -d '{"method":"getChat", "chat_id":"5139318475"}'

{"ok":false,"error_code":400,"description":"Bad Request: chat not found"}
~~~
