### ISSUE TITLE
推送报错

### ISSUE THREAD

**Issue by 907739769** [Ccccx159/Emby_Notifier#30]
[2024-12-23 19:28:41] [media.py|process_media|311] [INFO] : Received message: 新 猎罪图鉴 - S2, Ep22 - 第 22 集 在 放映厅

[2024-12-23 19:28:42] [tvdb_api.py|login|40] [ERROR] : TVDB login failed. InvalidAPIKey: apikey invalid Current API key: None

[2024-12-23 19:28:42] [media.py|get_details|184] [WARNING] : TVDB login failed. Check network connection or API key: 401 Client Error: Unauthorized for url: https://api4.thetvdb.com/v4/login

[2024-12-23 19:28:42] [media.py|_get_id|58] [INFO] : {"Name": "猎罪图鉴", "Type": "Episode", "PremiereYear": 1, "ProviderIds": {}, "Series": 22, "Season": 2}

[2024-12-23 19:28:47] [media.py|_get_id|75] [WARNING] : No matched media found for 猎罪图鉴 1 in TMDB.

[2024-12-23 19:28:47] [media.py|_get_id|79] [WARNING] : Use the first search result: 猎罪图鉴 2022.

[2024-12-23 19:28:50] [media.py|get_details|212] [ERROR] : No stills found for TV 139797 S2E22.

[2024-12-23 19:28:50] [media.py|get_details|213] [WARNING] : No still path found. use poster instead.

[2024-12-23 19:28:50] [sender.py|send_media_details|167] [ERROR] : Error sending media details by Telegram

[2024-12-23 19:28:50] [sender.py|send_media_details|168] [ERROR] : Traceback (most recent call last):

  File "/usr/src/myapp/sender.py", line 165, in send_media_details

    sender.send_media_details(media)

  File "/usr/src/myapp/sender.py", line 62, in send_media_details

    year=media["media_rel"][0:4],

         ~~~~~~~~~~~~~~~~~~^^^^^

TypeError: 'NoneType' object is not subscriptable

[2024-12-23 19:28:50] [media.py|process_media|329] [INFO] : Message processing completed: 新 猎罪图鉴 - S2, Ep22 - 第 22 集 在 放映厅

**Comment by Ccccx159** [comment]
以更新修复，最新镜像已推送docker hub
