### ISSUE TITLE
企业微信怎么弄啊？

### ISSUE THREAD

**Issue by Awhitedressy** [Ccccx159/Emby_Notifier#8]
WECHAT_CORP_ID=wXXXXXXXXa08
WECHAT_CORP_SECRET=1GGf9XXXXXXXXelFRB0wYuY
WECHAT_AGENT_ID=10XXXX

这几个变量加进去不行。

好像微信要调用API

**Comment by Awhitedressy** [comment]
![image](https://github.com/user-attachments/assets/ed7d2a58-0ab3-49fe-841e-0e5ac48b3fe7)
TG推送正常

**Comment by Ccccx159** [comment]
企业微信没打包，现在的docker hub上面的镜像版本落后于源码。微信的推送我只做了简单的功能验证，就没发布。有需要的话，我可以打个预发布的包先发布一个版本

**Comment by Awhitedressy** [comment]
需要，感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Ccccx159/Emby_Notifier"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月28日(星期天) 晚上11:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Ccccx159/Emby_Notifier] 企业微信怎么弄啊？ (Issue #8)





 
企业微信没打包，现在的docker hub上面的镜像版本落后于源码。微信的推送我只做了简单的功能验证，就没发布。有需要的话，我可以打个预发布的包先发布一个版本

**Comment by Ccccx159** [comment]
已经推送更新了，注意docker image镜像的tag为 Pre-release，用法和正式版一致哈

**Comment by Awhitedressy** [comment]
谢谢。这就去更新




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Ccccx159/Emby_Notifier"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月29日(星期一) 中午11:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Ccccx159/Emby_Notifier] 企业微信怎么弄啊？ (Issue #8)





 
已经推送更新了，注意docker image镜像的tag为 Pre-release，用法和正式版一致哈

**Comment by Awhitedressy** [comment]
> 已经推送更新了，注意docker image镜像的tag为 Pre-release，用法和正式版一致哈

有微信 openai 回调么？
    -e WECHAT_TOKEN="DKxxxxxxxxxxxCB2" \
    -e WECHAT_ENCODING_AES_KEY="ei9EjnFcymGExxxxxxxxxthSUhyts" \
没有用

**Comment by Ccccx159** [comment]
> > 已经推送更新了，注意docker image镜像的tag为 Pre-release，用法和正式版一致哈
> 
> 有微信 openai 回调么？ -e WECHAT_TOKEN="DKxxxxxxxxxxxCB2" -e WECHAT_ENCODING_AES_KEY="ei9EjnFcymGExxxxxxxxxthSUhyts" 没有用

这两个环境变量没有用，目前企业微信只做了自建应用推送。有效的环境变量只有以下几个：

| env | req | desc|
| --- | --- | --- |
| WECHAT_CORP_ID | 可选 | （企业微信）企业 id |
| WECHAT_CORP_SECRET | 可选 | （企业微信）应用的凭证秘钥 |
| WECHAT_AGENT_ID | 可选 | （企业微信）应用 agentid |
| WECHAT_USER_ID | 可选 | （企业微信）用户 id，默认为“@all” |

token 和 encoding aes key 这两个是用来设置应用API消息接收的，只有通过这个设置，才能设置可信ip，然后这个可信ip才能向对应的自建应用发送消息。否则所有向应用发送的消息都会被企业微信拦截，提示IP不可信。在完成应用的设置后，这两个值在本项目中其实是用不到的。可以google搜索一下“企业微信自定义应用 企业可信ip配置”

**Comment by Awhitedressy** [comment]
> > > 已经推送更新了，注意docker image镜像的tag为 Pre-release，用法和正式版一致哈
> > 
> > 
> > 有微信 openai 回调么？ -e WECHAT_TOKEN="DKxxxxxxxxxxxCB2" -e WECHAT_ENCODING_AES_KEY="ei9EjnFcymGExxxxxxxxxthSUhyts" 没有用
> 
> 这两个环境变量没有用，目前企业微信只做了自建应用推送。有效的环境变量只有以下几个：
> 
> env	req	desc
> WECHAT_CORP_ID	可选	（企业微信）企业 id
> WECHAT_CORP_SECRET	可选	（企业微信）应用的凭证秘钥
> WECHAT_AGENT_ID	可选	（企业微信）应用 agentid
> WECHAT_USER_ID	可选	（企业微信）用户 id，默认为“@ALL”
> token 和 encoding aes key 这两个是用来设置应用API消息接收的，只有通过这个设置，才能设置可信ip，然后这个可信ip才能向对应的自建应用发送消息。否则所有向应用发送的消息都会被企业微信拦截，提示IP不可信。在完成应用的设置后，这两个值在本项目中其实是用不到的。可以google搜索一下“企业微信自定义应用 企业可信ip配置”

是的，这两项主要是用来交互使用的。单推送确实用不到。我去google搜搜看怎么企业可信。

**Comment by Awhitedressy** [comment]
> > > > 已经推送更新了，注意docker image镜像的tag为 Pre-release，用法和正式版一致哈
> > > 
> > > 
> > > 有微信 openai 回调么？ -e WECHAT_TOKEN="DKxxxxxxxxxxxCB2" -e WECHAT_ENCODING_AES_KEY="ei9EjnFcymGExxxxxxxxxthSUhyts" 没有用
> > 
> > 
> > 这两个环境变量没有用，目前企业微信只做了自建应用推送。有效的环境变量只有以下几个：
> > env	req	desc
> > WECHAT_CORP_ID	可选	（企业微信）企业 id
> > WECHAT_CORP_SECRET	可选	（企业微信）应用的凭证秘钥
> > WECHAT_AGENT_ID	可选	（企业微信）应用 agentid
> > WECHAT_USER_ID	可选	（企业微信）用户 id，默认为“@ALL”
> > token 和 encoding aes key 这两个是用来设置应用API消息接收的，只有通过这个设置，才能设置可信ip，然后这个可信ip才能向对应的自建应用发送消息。否则所有向应用发送的消息都会被企业微信拦截，提示IP不可信。在完成应用的设置后，这两个值在本项目中其实是用不到的。可以google搜索一下“企业微信自定义应用 企业可信ip配置”
> 
> 是的，这两项主要是用来交互使用的。单推送确实用不到。我去google搜搜看怎么企业可信。



[2024-07-29 15:54:39] [media.py|process_media|309] [WARNING] : Unsupported event type: system.notificationtest
[2024-07-29 15:54:39] [media.py|process_media|311] [WARNING] : This is a notification test message. Please check your Telegram chat, if you received a message from Emby Notifier, it works!
[2024-07-29 15:54:39] [my_httpd.py|worker|22] [ERROR] : Traceback (most recent call last):
  File "/usr/src/myapp/my_httpd.py", line 20, in worker
    media.process_media(msg)
  File "/usr/src/myapp/media.py", line 312, in process_media
    Sender.send_test_msg(
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'send_test_msg'


企业IP，我通过域名已经配置上了。tg 也成功启动。就是用emby推送的时候出现错误，tg上也没有显示。
![image](https://github.com/user-attachments/assets/46e2eb0c-1f5d-49a9-ab33-9189eee6ccfc)
TG测试推送的话，应该显示这个的。通微信还有没有反应

**Comment by Ccccx159** [comment]
发送测试消息的接口调用有点问题，欢迎信息和正常媒体信息的推送应该不影响，企业微信没有收到欢迎消息吗？我本地测试欢迎信息两端都能收到的!

[image](https://github.com/user-attachments/assets/b0d3a6fc-5085-47e9-88ef-c128ae51fd20)

**Comment by Awhitedressy** [comment]
> 发送测试消息的接口调用有点问题，欢迎信息和正常媒体信息的推送应该不影响，企业微信没有收到欢迎消息吗？我本地测试欢迎信息两端都能收到的
> 
> ![image](https://private-user-images.githubusercontent.com/35327600/352974722-b0d3a6fc-5085-47e9-88ef-c128ae51fd20.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNDI0NDAsIm5iZiI6MTcyMjI0MjE0MCwicGF0aCI6Ii8zNTMyNzYwMC8zNTI5NzQ3MjItYjBkM2E2ZmMtNTA4NS00N2U5LTg4ZWYtYzEyOGFlNTFmZDIwLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOVQwODM1NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZDk3MDM1OGFhMDVkNWM0ZWFhMjEwZGRlMGJhYWVjOWMxMWYzMGQyNWQ4NTYwNWZmZjFkMTllMTQ1YWQzYWE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xb2v_otWtBUUJ_B5Kuv23qJkLy1FIBxSym_fuYII8Zc)

企业微信没有收到。 没有任何反应。

**Comment by Awhitedressy** [comment]
> > 发送测试消息的接口调用有点问题，欢迎信息和正常媒体信息的推送应该不影响，企业微信没有收到欢迎消息吗？我本地测试欢迎信息两端都能收到的
> > ![image](https://private-user-images.githubusercontent.com/35327600/352974722-b0d3a6fc-5085-47e9-88ef-c128ae51fd20.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNDI0NDAsIm5iZiI6MTcyMjI0MjE0MCwicGF0aCI6Ii8zNTMyNzYwMC8zNTI5NzQ3MjItYjBkM2E2ZmMtNTA4NS00N2U5LTg4ZWYtYzEyOGFlNTFmZDIwLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOVQwODM1NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZDk3MDM1OGFhMDVkNWM0ZWFhMjEwZGRlMGJhYWVjOWMxMWYzMGQyNWQ4NTYwNWZmZjFkMTllMTQ1YWQzYWE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xb2v_otWtBUUJ_B5Kuv23qJkLy1FIBxSym_fuYII8Zc)
> 
> 企业微信没有收到。 没有任何反应。

而且我必须加    -e WECHAT_USER_ID="@all" \ 这条变量才有反应。 不增加的话，容器会启动不了

**Comment by Ccccx159** [comment]
嗯，那个环境变量目前是必须的，容器起来的时候回校验环境变量，如果设置了企业id，则剩余微信相关环境变量任意一个不设置都会导致校验不通过。后面小版本更新我会去掉用户id的的校验。目前先设置一下吧

设置下log_level为DEBUG，然后重新启动服务，把完整的日志提供一下，注意信息脱敏。如果微信推送失败了，应该会有error错误日志

**Comment by Awhitedressy** [comment]
> 嗯，那个环境变量目前是必须的，容器起来的时候回校验环境变量，如果设置了企业id，则剩余微信相关环境变量任意一个不设置都会导致校验不通过。后面小版本更新我会去掉用户id的的校验。目前先设置一下吧
> 
> 设置下log_level为DEBUG，然后重新启动服务，把完整的日志提供一下，注意信息脱敏。如果微信推送失败了，应该会有error错误日志

[root@iZj6c6xchx1ftzykyuf80oZ ~]# docker logs embyts


███████╗███╗   ███╗██████╗ ██╗   ██╗    ███╗   ██╗ ██████╗ ████████╗██╗███████╗██╗███████╗██████╗
██╔════╝████╗ ████║██╔══██╗╚██╗ ██╔╝    ████╗  ██║██╔═══██╗╚══██╔══╝██║██╔════╝██║██╔════╝██╔══██╗
█████╗  ██╔████╔██║██████╔╝ ╚████╔╝     ██╔██╗ ██║██║   ██║   ██║   ██║█████╗  ██║█████╗  ██████╔╝
██╔══╝  ██║╚██╔╝██║██╔══██╗  ╚██╔╝      ██║╚██╗██║██║   ██║   ██║   ██║██╔══╝  ██║██╔══╝  ██╔══██╗
███████╗██║ ╚═╝ ██║██████╔╝   ██║       ██║ ╚████║╚██████╔╝   ██║   ██║██║     ██║███████╗██║  ██║
╚══════╝╚═╝     ╚═╝╚═════╝    ╚═╝       ╚═╝  ╚═══╝ ╚═════╝    ╚═╝   ╚═╝╚═╝     ╚═╝╚══════╝╚═╝  ╚═╝



Welcome to Emby Notifier!
Author: xu4n_ch3n
Version: 3.0.0
Update Time: 2024-07-29
Description: Emby Notifier is a media notification service for Emby Server. Now Jellyfin Server is alreay supported.
Repository: https://github.com/Ccccx159/Emby_Notifier



Checking environment variables...

--------Media Database info:
TMDB_API_TOKEN: (req) eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI2MTlkOWE3OTY0YmRlMmIzZGJlMTYwNjg3MmVhMTU5NCIsIm5iZiI6MTcyMjE1MzUyNS44NjY2MjEsInN1YiI6IjY1MTQ0YWE0YmRkNTY4MDBhZWM0OTQwNSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.Ty5AvPBGWKJqevKSwYd9Scu37EPnQSY3V9I0folP5pw
TVDB_API_KEY:   (opt) dc2fe540-e5b7-4c9d-a347-ccd54f042496

--------Telegram Bot info:
TG_BOT_TOKEN:   (req) 7068263152:AAHFioeiw6jKq32QItD0nHxx40XrgGLYlKs
TG_CHAT_ID:     (req) 7016579329

--------Wechat App info:
WECHAT_CORP_ID: (req) ww7bc058afa9369a08
WECHAT_CORP_SECRET: (req) 1GGf9mXOlR21PZjwIoalOFcS-ce9wTMllelFRB0wYuY
WECHAT_AGENT_ID: (req) 1000004
WECHAT_USER_ID: (req) @all

--------Log info:
LOG_LEVEL:      (opt) DEBUG
LOG_EXPORT:     (opt) False
LOG_PATH:       (opt) /var/tmp/emby_notifier_tg
[2024-07-29 16:49:12] [main.py|require_check|94] [INFO] : Checking requirements...
[2024-07-29 16:49:12] [main.py|require_check|97] [INFO] : Checking TMDB_API_TOKEN...
[2024-07-29 16:49:13] [tmdb_api.py|login|34] [INFO] : TMDB login successful.
[2024-07-29 16:49:13] [main.py|require_check|107] [INFO] : Checking TG_BOT_TOKEN...
[2024-07-29 16:49:13] [tgbot.py|bot_authorization|51] [DEBUG] : {"ok":true,"result":{"id":70*****3152,"is_bot":true,"first_name":"AWdress- \u5f71\u89c6\u66f4\u65b0","username":"AWDys_bot","can_join_groups":true,"can_read_all_group_messages":false,"supports_inline_queries":false,"can_connect_to_business":false}}
[2024-07-29 16:49:13] [tgbot.py|bot_authorization|52] [INFO] : Telegram bot authorization successful. Current bot: AWDys_bot
[2024-07-29 16:49:13] [main.py|require_check|111] [INFO] : Checking TG_CHAT_ID...
[2024-07-29 16:49:15] [tgbot.py|get_chat|68] [DEBUG] : {"ok":true,"result":{"id":70*****9329,"first_name":"Awhitedress","username":"AWdress","type":"private","active_usernames":["AWdress"],"photo":{"small_file_id":"AQADBQADtrwxG1jWIFcACAIAAwGBOKIBAANf_CVBG0C8CzUE","small_file_unique_id":"AQADtrwxG1jWIFcAAQ","big_file_id":"AQADBQADtrwxG1jWIFcACAMAAwGBOKIBAANf_CVBG0C8CzUE","big_file_unique_id":"AQADtrwxG1jWIFcB"},"max_reaction_count":11,"accent_color_id":4}}
[2024-07-29 16:49:15] [tgbot.py|get_chat|71] [INFO] : Telegram getChat successful. Chat User: [AWdress], type: private
[2024-07-29 16:49:15] [tgbot.py|send_message|20] [DEBUG] : {"method": "sendMessage", "chat_id": "70*****9329", "text": "Welcome to Emby Notifier!\nAuthor: xu4n\\_ch3n\nVersion: 3.0.0\nUpdate Time: 2024-07-29\nDescription: Emby Notifier is a media notification service for Emby Server. Now Jellyfin Server is alreay supported.\nRepository: https://github.com/Ccccx159/Emby\\_Notifier\n", "parse_mode": "Markdown"}
[2024-07-29 16:49:15] [wxapp.py|send_welcome_card|202] [DEBUG] : {"touser": "@all", "agentid": 10*****0004, "safe": 0, "msgtype": "template_card", "template_card": {"card_type": "text_notice", "source": {"desc": "🚀 Emby Notifier", "desc_color": 0}, "main_title": {"title": "🎉 Welcome to Emby Notifier!"}, "quote_area": {"quote_text": "Emby Notifier is a media notification service for Emby Server. Now Jellyfin Server is alreay supported."}, "horizontal_content_list": [{"keyname": "Author", "value": "xu4n_ch3n"}, {"keyname": "Version", "value": "3.0.0"}, {"keyname": "Update Time", "value": "2024-07-29"}], "jump_list": [{"type": 1, "url": "https://github.com/Ccccx159/Emby_Notifier", "title": "👾 github"}], "card_action": {"type": 1, "url": "https://github.com/Ccccx159/Emby_Notifier"}}}
[2024-07-29 16:49:16] [wxapp.py|get_access_token|65] [DEBUG] : {"errcode":0,"errmsg":"ok","access_token":"5i5FkjDnhVeDcADpq8V_ROKUJW4tio7TmDFwudPE1Eot_Hea9f0LQ6d4XqBy-S1JXYhi-IaNK2YUD0UKanmHKgEXlnEI-P6ozfQWo-jdjCt3ZH_IFqpZ2_ijysjYgikoehSehYMosSLRPUo1_bfK_jNpSqu7WlXrxxGIcHinZCoyYBhF4SpRYmExPlrPl9mP4K5co9MeEMe5fVmvj8Pvpg","expires_in":7200}
[2024-07-29 16:49:16] [wxapp.py|get_access_token|70] [INFO] : Update access token successful. Token: 5i5FkjDnhVeDcADpq8V_ROKUJW4tio7TmDFwudPE1Eot_Hea9f0LQ6d4XqBy-S1JXYhi-IaNK2YUD0UKanmHKgEXlnEI-P6ozfQWo-jdjCt3ZH_IFqpZ2_ijysjYgikoehSehYMosSLRPUo1_bfK_jNpSqu7WlXrxxGIcHinZCoyYBhF4SpRYmExPlrPl9mP4K5co9MeEMe5fVmvj8Pvpg
[2024-07-29 16:49:16] [wxapp.py|send_welcome_card|210] [DEBUG] : Send news notice successful. Response: {'errcode': 0, 'errmsg': 'ok', 'msgid': 'Dv0oBVNA9p2BIWPODPqgkgJStQet7BuJQeAmVwzj1hjupUZeaAceGpjvdQKhqxQry8a67zQA5yJi-tPl6DJn4w'}
[2024-07-29 16:49:16] [my_httpd.py|worker|9] [INFO] : Emby Notifier started.
[2024-07-29 16:49:16] [my_httpd.py|my_httpd|63] [INFO] : HTTP server started at http://localhost:8000

**Comment by Ccccx159** [comment]
你是不是用的微信里面的企业微信插件，我用了卡片模板中的"文本通知型"和"图文展示型"的消息类型，这两种消息是无法在插件中显示的，只能用企业微信本体软件里面接收。

**Comment by Awhitedressy** [comment]
> 你是不是用的微信里面的企业微信插件，我用了卡片模板中的"文本通知型"和"图文展示型"的消息类型，这两种消息是无法在插件中显示的，只能用企业微信本体软件里面接收。

哈哈哈，还真是，我打开企业微信app 成功看到了，不好意思了。打扰这么久。

**Comment by Awhitedressy** [comment]
> > 你是不是用的微信里面的企业微信插件，我用了卡片模板中的"文本通知型"和"图文展示型"的消息类型，这两种消息是无法在插件中显示的，只能用企业微信本体软件里面接收。
> 
> 哈哈哈，还真是，我打开企业微信app 成功看到了，不好意思了。打扰这么久。

不过还是推荐大大 适配一下插件，必须微信方便，只是提个建议。。

**Comment by Ccccx159** [comment]
> > > 你是不是用的微信里面的企业微信插件，我用了卡片模板中的"文本通知型"和"图文展示型"的消息类型，这两种消息是无法在插件中显示的，只能用企业微信本体软件里面接收。
> > 
> > 
> > 哈哈哈，还真是，我打开企业微信app 成功看到了，不好意思了。打扰这么久。
> 
> 不过还是推荐大大 适配一下插件，必须微信方便，只是提个建议。。

后面有空再弄吧，换了工作忙成狗 T T 【另一个支持 arm 的 issue 我也还来得及弄，都不敢回复】

微信插件有点辣鸡，适配的话估计只能是普通的图文消息了，和当前的消息类型会不兼容，到时候只能开个环境变量配置选择其中一种了，否则会导致同一影片信息的重复推送。不知道微信插件为啥不支持复杂类型的消息（辣鸡）
